import type { Metadata } from "next";
// import "@styles/reset.css";
import "@styles/globals.css";
// import "@styles/theme.scss";
import { ClientProviders } from "@ui/utilities/client-providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-red-100">
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
