import type { Metadata } from "next";
import "@styles/globals.scss";
import { Layout } from "@ui/layout/layout";
import { ClientProviders } from "@ui/utilities/client-providers";
import "/node_modules/flag-icons/css/flag-icons.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme-color="blue">
      <body className="bg-background"> 
        <ClientProviders>
          <Layout>
            {children}
          </Layout>
        </ClientProviders>
      </body>
    </html>
  );
}
